# https://github.com/argoproj/argo-events/blob/master/examples/event-sources/github.yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: bradfordwagner
  namespace: argo-events
spec:
  github:
    bradfordwagner:
      repositories:
        - owner: bradfordwagner
          names:
            - container-base
            - container-kaniko
            - container-argo
            - container-ansible
            - container-go-builder
            - ks
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: http://bradfordwagner.com:12000
#        serverCertSecret:
#          name: eventsource-tls
#          key: certificate
#        serverKeySecret:
#          name: eventsource-tls
#          key: private_key
      events:
        - "*"
      apiToken:
        name: github-access-token
        key: token
      insecure: true
      active: true
      contentType: json
