---

github:
  eventsource:
    host: bradfordwagner.com
    port: 30000
    nodePort: 30000

  repositories:
    - owner: bradfordwagner
      names:
        - container-base
        - container-kaniko
        - container-argo
        - container-ansible
        - container-go-builder
        - container-manifest-tool
        - container-ansible-role-builder
        - container-vault
        - container-vault-k8s-auth
        - container-terraform
        - container-redis
        - ansible-role-helloworld
        - tf-vault-infra
        - tf-testbed
        - tf-vault-policy
        - tf-az-infra
        - ansible-role-azure-blob-cli
        - ansible-role-gitops-toolkit
        - ansible-role-jumpdir
        - devtainer
        - container-secrets-store-csi-driver

        # go app
        - ks
        - go-azure-blob-cli
        - go-cli-jumpdir

        # go libs
        - go-kafka-dao
        - go-threadpool
        - go-util

        # gh templates
        - gh-template-go-cli
        - gh-template-go-lib
        - gh-template-mirror-image
        - gh-template-ansible-role
        - gh-template-ansible-playbook

