# https://github.com/argoproj/argo-events/blob/master/examples/event-sources/github.yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: bradfordwagner
  namespace: {{ .Release.Namespace }}
spec:
  template:
    # include csi secret from vault
    container:
      volumeMounts:
        - name: github-token
          mountPath: /mnt/github_token
          readOnly: true
    volumes:
      - name: github-token
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: argo-events-webhook
  github:
    bradfordwagner:
      repositories: {{- .Values.github.repositories | toYaml | nindent 9 }}
      webhook:
        endpoint: /push
        port: {{ .Values.github.eventsource.port | quote }}
        method: POST
        url: http://{{ .Values.github.eventsource.host }}:{{ .Values.github.eventsource.port }}
#       url: https://{{ .Values.github.eventsource.host }}:{{ .Values.github.eventsource.port }}
#       serverCertSecret:
#         name: github-access
#         key: certificate
#       serverKeySecret:
#         name: github-access
#         key: private-key
#       webhookSecret:
#         name: github-access
#         key: github-secret
      events:
        - "*"
      apiToken:
        # pull in secret from csi storage class below
        name: github-access
        key: token
#     insecure: false
      insecure: true
      active: true
      contentType: json
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: argo-events-webhook
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  secretObjects:
    - secretName: github-access
      type: Opaque
      data:
        - objectName: token
          key: token
        - objectName: private-key
          key: private-key
        - objectName: certificate
          key: certificate
#       - objectName: githhub-secret
#         key: github-secret
  parameters:
    roleName: bradford_argo_events_reader
    objects: |
      - objectName: token
        secretPath: secret/data/bradford_argo_events
        secretKey: github_access_token
      - objectName: private-key
        secretPath: secret/data/bradford_argo_events
        secretKey: private_key
      - objectName: certificate
        secretPath: secret/data/bradford_argo_events
        secretKey: certificate
      - objectName: github-secret
        secretPath: secret/data/bradford_argo_events
        secretKey: github_secret

