apiVersion: v1
kind: Service
metadata:
  name: github-webhook
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 12000
      protocol: TCP
      targetPort: 12000
  selector:
    eventsource-name: bradfordwagner
  type: LoadBalancer
