# https://github.com/argoproj/argo-events/blob/master/examples/event-sources/github.yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: bradfordwagner
  namespace: {{ .Release.Namespace }}
spec:
  github:
    bradfordwagner:
      repositories:
        - owner: bradfordwagner
          names:
            - container-base
            - container-kaniko
            - container-argo
            - container-ansible
            - container-go-builder
            - ks
            - container-manifest-tool
      webhook:
        endpoint: /push
        port: {{ .Values.github.eventsource.port | quote }}
        method: POST
        url: http://{{ .Values.github.eventsource.host }}:{{ .Values.github.eventsource.port }}
#        serverCertSecret:
#          name: eventsource-tls
#          key: certificate
#        serverKeySecret:
#          name: eventsource-tls
#          key: private_key
      events:
        - "*"
      apiToken:
        name: github-access-token
        key: token
      insecure: true
      active: true
      contentType: json
