{{ $service_account_name := printf "%s-sensor" .Release.Name }}
{{ $role_name := "workflow-creator"}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $service_account_name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $role_name }}
rules:
  - apiGroups: [argoproj.io]
    verbs: ["*"]
    resources: [workflows]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $role_name }}
subjects:
  - kind: ServiceAccount
    name: {{ $service_account_name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $role_name }}
  apiGroup: rbac.authorization.k8s.io